<?php
// $Id:

/**
 *
 */

define('UC_TERMSOFSERVICE_CART', 1);
define('UC_TERMSOFSERVICE_CHECKOUT', 2);

/**
 * Implementation of hook_menu()
 */
function uc_termsofservice_menu() {
  $items = array();

  $items['admin/store/settings/tos'] = array(
    'title'             => 'Terms of Service',
    'description'       => 'Ubercart Terms of Service check for cart/checkout',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('uc_termsofservice_admin_settings'),
    'access arguments'  => array('administer store'),
    'file'              => 'uc_termsofservice.admin.inc',
  );

  $items['uc_termsofservice/node/autocomplete'] = array(
    'title'             => 'Autocomplete of nodes',
    'page callback'     => 'uc_termsofservice_node_autocomplete',
    'access callback'   => TRUE,
    'file'              => 'uc_termsofservice.admin.inc',
    'type'              => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_theme()
 */
function uc_termsofservice_theme() {
  return array(
    'uc_termsofservice_agreement_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'uc_termsofservice_agreement_form',
    ),
  );
}

/**
 * Ubercart hooks
 */

/**
 * Implementation of hook_cart_pane().
 */
function uc_termsofservice_cart_pane($items) {
  $status = FALSE;
  if (variable_get('tos_target', 0) == UC_TERMSOFSERVICE_CART) {
    $status = TRUE;
  }
  $panes[] = array(
    'id' => 'uc_termsofservice_agreement_cart',
    'title' => t('Terms and conditions agreement'),
    'desc' => t("Please confirm if you agree with our terms and conditions that apply on all our purchases."),
    'weight' => 6,
    'enabled' => $status,
    'body' => !is_null($items) ? drupal_get_form('uc_termsofservice_cart_form', $items) : '',
  );
  return $panes;
}

/**
 * Implementation of hook_checkout_pane().
 */
function uc_termsofservice_checkout_pane() {
  $status = FALSE;
  if (variable_get('tos_target', 0) == UC_TERMSOFSERVICE_CHECKOUT) {
    $status = TRUE;
  }
  $panes[] = array(
    'id' => 'uc_termsofservice_agreement_checkout',
    'callback' => 'uc_termsofservice_checkout_pane_callback',
    'title' => t('Terms and conditions agreement'),
    'desc' => t("Please confirm if you agree with our terms and conditions that apply on all our purchases."),
    'weight' => 6,
    'enabled' => $status,
    'collapsible' => TRUE,
  );
  return $panes;
}

function uc_termsofservice_cart_form($items) {
  $form = uc_termsofservice_general_form();
  return $form;
}

/**
 * General form for both checkout & cart modes
 */
function uc_termsofservice_general_form() {
  $form = array();
  $nid = uc_termsofservice_get_nid_from_variable();
  if ($nid) {
    $required = variable_get('tos_required', 0);
    if (module_exists('translation')) {
      global $language;
      $translations = translation_node_get_translations($nid);
      if ($translations[$language->language]) {
        $nid = $translations[$language->language]->nid;
      }
    }
    $node = node_load($nid);

    $form['tos_text'] = array(
      '#value' => $node->body,
    );
    $form['tos_agree'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Terms of Service'),
      '#options' => array(t('I agree with the Terms of Service')),
      '#required' => $required,
    );

    $form['#theme'] = 'uc_termsofservice_agreement_form';
    return $form;
  }
  return;
}

function uc_termsofservice_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'uc_cart_view_form' && variable_get('tos_target', 0) == UC_TERMSOFSERVICE_CART && variable_get('tos_required', 0)) {
    $form['#validate'][] = 'uc_termsofservice_validate_required';
  }
}

function uc_termsofservice_validate_required($form, &$form_state) {
}

function uc_termsofservice_checkout_pane_callback($op) {
  switch ($op) {
    case 'view':
      $form = uc_termsofservice_general_form();
      return array('contents' => $form, 'next-button' => FALSE);
      break;
  }
}

function uc_termsofservice_get_nid_from_variable() {
  $tos_node = variable_get('tos_node', 0);
  $preg_matches = array();
  $match = preg_match('/\[nid: (\d+)\]/',$tos_node, $preg_matches);
  if ($match) {
    $nid = $preg_matches[1];
  }
  return $nid;
}