<?php
// $Id$

/**
 * Ubercart Terms of Service.
 * @author: pcambra.
 */

/**
 * Constants for admin settings page.
 */
define('UC_TERMSOFSERVICE_CART', 1);
define('UC_TERMSOFSERVICE_CHECKOUT', 2);

/**
 * Implementation of hook_menu()
 */
function uc_termsofservice_menu() {
  $items = array();

  $items['admin/store/settings/tos'] = array(
    'title'             => 'Terms of Service',
    'description'       => 'Ubercart Terms of Service check for cart/checkout',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('uc_termsofservice_admin_settings'),
    'access arguments'  => array('administer store'),
    'file'              => 'uc_termsofservice.admin.inc',
  );

  $items['uc_termsofservice/node/autocomplete'] = array(
    'title'             => 'Autocomplete of nodes',
    'page callback'     => 'uc_termsofservice_node_autocomplete',
    'access callback'   => TRUE,
    'file'              => 'uc_termsofservice.admin.inc',
    'type'              => MENU_CALLBACK,
  );

  /**
   * modalframe callback items
   */
  if (module_exists('modalframe')) {
    $items['uc_termsofservice/show'] = array(
      'title'             => 'Show Terms of Service',
      'page callback'     => 'drupal_get_form',
      'page arguments'    => array('uc_termsofservice_general_form'),
      'access callback'   => TRUE,
      'type'              => MENU_CALLBACK,
    );
  }

  return $items;
}

/**
 * Implementation of hook_theme()
 */
function uc_termsofservice_theme() {
  return array(
    'uc_termsofservice_agreement_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'uc_termsofservice_agreement_form',
    ),
    'uc_termsofservice_agreement_node' => array(
      'arguments' => array('node' => NULL),
      'template' => 'uc_termsofservice_agreement_node',
    ),
  );
}

/**
 * Ubercart hooks
 */

/**
 * Implementation of hook_cart_pane().
 */
function uc_termsofservice_cart_pane($items) {
  $status = FALSE;
  if (variable_get('tos_target', 0) == UC_TERMSOFSERVICE_CART) {
    $status = TRUE;
  }
  $panes[] = array(
    'id' => 'uc_termsofservice_agreement_cart',
    'title' => t('Terms and conditions agreement'),
    'desc' => t("Please confirm if you agree with our terms and conditions that apply on all our purchases."),
    'weight' => 6,
    'enabled' => $status,
    'body' => !is_null($items) ? drupal_get_form('uc_termsofservice_agreement_cart_callback', $items) : '',
  );
  return $panes;
}

/**
 * Implementation of hook_checkout_pane().
 */
function uc_termsofservice_checkout_pane() {
  $status = FALSE;
  if (variable_get('tos_target', 0) == UC_TERMSOFSERVICE_CHECKOUT) {
    $status = TRUE;
  }
  $panes[] = array(
    'id' => 'uc_termsofservice_agreement_checkout',
    'callback' => 'uc_termsofservice_checkout_pane_callback',
    'title' => t('Terms and conditions agreement'),
    'desc' => t("Please confirm if you agree with our terms and conditions that apply on all our purchases."),
    'weight' => 6,
    'enabled' => $status,
    'collapsible' => TRUE,
  );
  return $panes;
}

/**
 * Callback form for cart pane.
 */
function uc_termsofservice_agreement_cart_callback($items) {
  if (module_exists('modalframe') && variable_get('tos_popup', 0)) {
    // If the modalframe module is enabled and the config for popups is
     // then the ToS is shown in a popup
    modalframe_parent_js();
    drupal_add_js(drupal_get_path('module', 'uc_termsofservice') .'/uc_termsofservice.js');
    $node = uc_termsofservice_get_node();
    $form = uc_termsofservice_get_item($node->title, 'uc_termsofservice/show', '500,300');
  }
  else {
    $form = uc_termsofservice_general_form();
  }
  return $form;
}

/**
 * General form for both checkout & cart modes
 */
function uc_termsofservice_general_form() {
  $form = array();
  $node = uc_termsofservice_get_node();
  $required = variable_get('tos_required', 0);
  $form['tos_text'] = array(
    '#value' => theme('uc_termsofservice_agreement_node', $node),
  );
  $form['tos_agree'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Terms of Service'),
    '#options' => array('agreed' => t('I agree with the Terms of Service')),
    '#required' => $required,
  );
  $form['#theme'] = 'uc_termsofservice_agreement_form';

  if (module_exists('modalframe') && variable_get('tos_popup', 0)) {
    // Send the Modal Frame javascript for child windows to the page.
    modalframe_child_js();
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
    $form['tos_agree']['#attributes'] = array('onclick' => 'this.form.submit();');
  }
  return $form;
}

function uc_termsofservice_general_form_submit($form, &$form_state) {
  modalframe_close_dialog(array('tos_selected' => $form_state['values']['tos_agree']));
}

/**
 * Callback form for checkout pane.
 */
function uc_termsofservice_checkout_pane_callback($op) {
  switch ($op) {
    case 'view':
      if (module_exists('modalframe') && variable_get('tos_popup', 0)) {
        // If the modalframe module is enabled and the config for popups is
         // then the ToS is shown in a popup
        modalframe_parent_js();
        drupal_add_js(drupal_get_path('module', 'uc_termsofservice') .'/uc_termsofservice.js');
        $node = uc_termsofservice_get_node();
        $form = uc_termsofservice_get_item($node->title, 'uc_termsofservice/show', '500,300');
      }
      else {
        $form = uc_termsofservice_general_form();
      }
      return array('contents' => $form, 'next-button' => FALSE);
      break;
  }
}

/**
 * Function that filters the node nid from the autocomplete string.
 */
function uc_termsofservice_get_nid_from_variable() {
  $tos_node = variable_get('tos_node', 0);
  $preg_matches = array();
  $match = preg_match('/\[nid: (\d+)\]/', $tos_node, $preg_matches);
  if ($match) {
    $nid = $preg_matches[1];
  }
  return $nid;
}

/**
 * Retrieves the ToS node from database.
 */
function uc_termsofservice_get_node($nid = NULL) {
  if (!$nid) {
    $nid = uc_termsofservice_get_nid_from_variable();
  }
  if ($nid) {
    if (module_exists('translation')) {
      global $language;
      $translations = translation_node_get_translations($nid);
      if ($translations[$language->language]) {
        $nid = $translations[$language->language]->nid;
      }
    }
    $node = node_load($nid);
    return $node;
  }
  return;
}

/**
 * Helper function for ModalFrame to build links to popup page.
 */
function uc_termsofservice_get_item($title, $path, $size = NULL) {
  $options = array('attributes' => array('class' => 'uc_termsofservice-child'. (!empty($size) ? ' uc_termsofservice-size['. $size .']' : '')));
  $required = variable_get('tos_required', 0);
  $form['tos_agree_popup'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Terms of Service'),
    '#options' => array('agreed' => t('I agree with the !tos', array('!tos' => l($title, $path, $options)))),
    '#required' => $required,
  );
  return $form;
}